name: exatrkx-hsf

channels:
    - defaults
    - pytorch
    - pyg
    - conda-forge
    
dependencies:
    - pip
    - numpy
    - pandas
    - scipy
    - matplotlib
    - cpuonly
    - pytorch==1.10.2
    - pytorch-lightning
    - pyg
    - faiss-cpu
